### ISSUE TITLE
Completed module 2 assignments

### ISSUE THREAD

**Issue by charlottemeyer** [rbtl-fs24/md-02-assignments-charlottemeyer#1]
@larnsce

Quick question:
I had this message when I wanted to commit my changes:

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'r2515670@application-11405479-deployment-21599140-qrlkm.(none)')

I could not figure out how to fix it.

**Comment by larnsce** [comment]
Hi @charlottemeyer , has this worked for you by now? It has to do with the git configuration, which unexpectedly did not translate over to this project.

Try to go back to assignment 1 of module 2 and copy the code-chunk where you edited your details into the .qmd file for this assignment. Run the code-chunk, and git should know who you are and allow you to make a commit.

**Comment by charlottemeyer** [comment]
Hi @larnsce , yes I could figure it out, thank you for asking!
